---
version: "3.1"

services:
  web:
    container_name: school-registration
    platform: linux/amd64
    ports:
      - "8080"
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - GRADLE_USER_HOME=cache
      - MYSQL_URL=localhost:3307
      - MYSQL_DB_NAME=school-registration-db
      - MYSQL_USERNAME=root
      - MYSQL_PASS=mysqlpass

  db:
    image: mysql:8
    platform: linux/amd64
    container_name: school-registration-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: school-registration-db
      MYSQL_ROOT_PASSWORD: mysqlpass